# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-05 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190304_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 7, 8, 23, 847760, tzinfo=utc)),
        ),
    ]
